### ISSUE TITLE
Explicit Setup

### ISSUE THREAD

**Issue by mslinn** [runarorama/latr#1]
Trying to figure out how to add `latr` to an existing SBT project is a bit of a research project. Would you please add explicit instructions on how to do that, assuming:

 * build.sbt syntax is used, with SBT 0.13.11
 * Project has multiple dependencies 
 * No subprojects (document that separately if desired)
 * Existing project uses typical Maven-style directories
 * Examples for Scala 2.10.6 and 2.11.8

Thank you!

**Comment by runarorama** [comment]
There is no support for Scala 2.10 at the moment, but I'm hoping some kind soul will submit a PR for that.

Leaving this open to add more detailed instructions for more complex situations, but your SBT project sounds pretty straightforward. To add Latr, you probably just have to:

1. Add Macro Paradise to your build.sbt with `addCompilerPlugin`
2. Add a resolver to Latr's bintray repo.
3. Add Latr to your `libraryDependencies`
4. Profit!

**Comment by runarorama** [comment]
Added some more details in the README

**Comment by mslinn** [comment]
Nice! Thanks for responding so quickly. I put together a [small sample project](https://github.com/mslinn/latrExample).
