### ISSUE TITLE
'var $haz: Boolean = _' should be volatile for lazifyMacro

### ISSUE THREAD

**Issue by armsargis** [runarorama/latr#2]
I think 'var $haz: Boolean = _' should be volatile for lazifyMacro, otherwise its possible that value written to it will not be published to main memory and will not be visible for other threads and evaluation will happens many times.

**Comment by runarorama** [comment]
That's fine. The `lazify` macro is for the common case where you don't care about multiple threads recomputing the value. Even if we do make it `volatile`, evaluation may happen multiple times before the volatile write. And then a bunch of threads will all make this same write. If you want any guarantees of "once and only once" semantics, use `lazifyPessimistic` or `lazifyOptimistic`.

**Comment by runarorama** [comment]
I did a bit of testing with this, and it appears that using a `volatile var` actually makes the value _more_ likely to be recomputed under contention (since it takes longer to complete the write).
